const en = {
  create: 'Create new',
  back: 'Back',
  undo: 'Undo',
  close: 'Close',
  save: 'Save',
  remove: 'Remove',
  edit: 'Edit',
  on: 'On',
  off: 'Off',
  create_requirement: 'Add requirement',
  assign: 'Assign',
  update: 'Update',
  send: 'Send',
  authenticate: 'Authenticate',
  unauthenticate: 'Unauthenticate',
  open_feature: 'Open feature',
  confirm: 'Confirm',
  cancel: 'Cancel',
  selectRoadmap: 'Select roadmap',
  exportToGitLab: 'Export to GitLab',
};

const fi: typeof en = {
  create: 'Luo uusi',
  back: 'Takaisin',
  undo: 'Kumoa',
  close: 'Sulje',
  save: 'Tallenna',
  remove: 'Poista',
  edit: 'Muokkaa',
  on: 'Päällä',
  off: 'Pois',
  create_requirement: 'Lisää vaatimus',
  assign: 'Merkkaa toimeksianto',
  update: 'Päivitä',
  send: 'Lähetä',
  authenticate: 'Autentikoi',
  unauthenticate: 'Poista autentikointi',
  open_feature: 'Avaa ominaisuus',
  confirm: 'Vahvista',
  cancel: 'Peruuta',
  selectRoadmap: 'Valitse roadmap',
  exportToGitLab: 'Vie GitLabiin',
};

export default { en, fi };
