const en: { [key: string]: string } = {
  _id: 'Id',
  name: 'Name',
  filter: 'Filter',
  roadmap: 'Roadmap',
  archived: 'Archived',
  version: 'Version',
  tags: 'Tags',
  products: 'Products',
  requirements: 'Requirements',
  assignments: 'Assignments',
  weight: 'Weight',
  color: 'Color',
  workHoursEstimate: 'Work hours estimate (h)',
  hourPrice: 'Hour price (€/h)',
  user: 'User',
  comment: 'Comment',
  done: 'Done',
  fulfilled: 'Fulfilled',
  functional: 'Functional requirement',
  value: 'Value',
  major: 'Major',
  minor: 'Minor',
  codename: 'Codename',
  balance: 'Balance',
  comments: 'Comments',
  assignee: 'Assignee',
  feature: 'Feature',
  defaultRoadmapId: 'Default roadmap',
  roadmapIds: 'My roadmaps',
  archival: 'Archival',
};

const fi: typeof en = {
  _id: 'Tunniste',
  name: 'Nimi',
  filter: 'Suodata',
  roadmap: 'Roadmap',
  archived: 'Arkistoitu',
  version: 'Julkaisuversio',
  tags: 'Tagit',
  products: 'Tuotteet',
  requirements: 'Vaatimukset',
  assignments: 'Toimeksiannot',
  weight: 'Painoarvo',
  color: 'Väri',
  workHoursEstimate: 'Työmääräarvio (h)',
  hourPrice: 'Tuntihinta (€/h)',
  user: 'Käyttäjä',
  comment: 'Kommentti',
  done: 'Valmis',
  fulfilled: 'Toteutuu',
  functional: 'Funktionaalinen vaatimus',
  value: 'Arvo',
  major: 'Major',
  minor: 'Minor',
  codename: 'Koodinimi',
  balance: 'Painopiste',
  comments: 'Kommentit',
  assignee: 'Omistaja',
  feature: 'Ominaisuus',
  defaultRoadmapId: 'Oletusroadmap',
  roadmapIds: 'Minun roadmapit',
  archival: 'Arkistointi',
};

export default { en, fi };
