const fi: { [key: string]: string } = {
  _id: 'Tunniste',
  name: 'Nimi',
  filter: 'Suodata',
  roadmap: 'Roadmap',
  archived: 'Arkistoitu',
  version: 'Julkaisuversio',
  tags: 'Tagit',
  products: 'Tuotteet',
  requirements: 'Vaatimukset',
  assignments: 'Toimeksiannot',
  weight: 'Painoarvo',
  color: 'Väri',
  workHoursEstimate: 'Työmääräarvio (h)',
  hourPrice: 'Tuntihinta (€/h)',
  user: 'Käyttäjä',
  comment: 'Kommentti',
  done: 'Valmis',
  fulfilled: 'Toteutuu',
  value: 'Arvo',
  major: 'Major',
  minor: 'Minor',
  codename: 'Koodinimi',
  balance: 'Painopiste',
  comments: 'Kommentit',
  assignee: 'Omistaja',
  feature: 'Ominaisuus',
  defaultRoadmapId: 'Oletusroadmap',
  roadmapIds: 'Minun roadmapit',
  archival: 'Arkistointi',
};

export default { fi };
